
Maci\OrderBundle\Entity\Item:
    type:  entity
    table: maci_order_item
    repositoryClass: Maci\OrderBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        info:
            type: text
            nullable: true
        details:
            type: text
            nullable: true
        quantity:
            type: decimal
            nullable: true
        amount:
            type: decimal
            nullable: true
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: items
            joinColumn:
                name: order_id
                referencedColumnName: id
        product:
            targetEntity: Maci\ProductBundle\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setUpdatedValue, setCreatedValue ]
        preUpdate: [ setUpdatedValue ]

