
Maci\OrderBundle\Entity\Payment:
    type:  entity
    table: maci_order_payment
    #repositoryClass: Maci\OrderBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setCreatedValue ]
