

maci_order_edit_cart_item:
    pattern:  /order/cart-item/{id}/edit
    defaults: { _controller: MaciOrderBundle:Default:editCartItem }

maci_order_remove_cart_item:
    pattern:  /order/cart-item/{id}/remove
    defaults: { _controller: MaciOrderBundle:Default:removeCartItem }

maci_order_checkout:
    pattern:  /order/checkout/{id}
    defaults: { _controller: MaciOrderBundle:Default:checkout }

maci_order_invoice:
    pattern:  /order/invoice/{id}
    defaults: { _controller: MaciOrderBundle:Default:invoice }

# maci_order_test:
#     pattern:  /order/test/{id}
#     defaults: { _controller: MaciOrderBundle:Default:test, id: 0 }

maci_order_paypal_complete:
    pattern:  /order/paypal/complete
    defaults: { _controller: MaciOrderBundle:Default:paypalComplete }

maci_order_paypal_ipn:
    pattern:  /order/paypal/ipn
    defaults: { _controller: MaciOrderBundle:Ipn:index }

maci_order_cart_form:
    pattern:  /order/cart/form
    defaults: { _controller: MaciOrderBundle:Default:cartForm }

maci_order_cart_add:
    pattern:  /order/cart/add
    defaults: { _controller: MaciOrderBundle:Default:addToCart }

maci_order_cart:
    pattern:  /order/cart
    defaults: { _controller: MaciOrderBundle:Default:cart }

maci_order_notfound:
    pattern:  /order/notfound
    defaults: { _controller: MaciOrderBundle:Default:notfound }

maci_order:
    pattern:  /order
    defaults: { _controller: MaciOrderBundle:Default:index }

