

maci_paypal_ipn:
    pattern:  /ipn/ipn-twig-email-notification
    defaults: { _controller: MaciOrderBundle:TwigNotificationEmail:index }


maci_order_cart_add:
    pattern:  /cart/item/add/{product}
    defaults: { _controller: MaciOrderBundle:Default:addToCart }

maci_order_edit_cart_item:
    pattern:  /cart/item/edit/{id}
    defaults: { _controller: MaciOrderBundle:Default:editCartItem }

maci_order_remove_cart_item:
    pattern:  /cart/item/remove/{id}
    defaults: { _controller: MaciOrderBundle:Default:removeCartItem }

maci_order_checkout_set_address:
    pattern:  /cart/checkout/set-address/{option}
    defaults: { _controller: MaciOrderBundle:Default:cartSetAddress }

maci_order_gocheckout:
    pattern:  /cart/gocheckout/{option}
    defaults: { _controller: MaciOrderBundle:Default:cartGoCheckout, option: checkout }

maci_order_invoice:
    pattern:  /order/invoice/{id}
    defaults: { _controller: MaciOrderBundle:Default:invoice }

maci_order_checkout_set_checkout:
    pattern:  /cart/checkout/set-checkout/{checkout}
    defaults: { _controller: MaciOrderBundle:Default:cartSetCheckout, checkout: checkout }

maci_order_checkout_set_mail:
    pattern:  /cart/checkout/set-mail
    defaults: { _controller: MaciOrderBundle:Default:cartSetMail }

maci_order_checkout_set_payment:
    pattern:  /cart/checkout/set-payment
    defaults: { _controller: MaciOrderBundle:Default:cartSetPayment }

maci_order_checkout_set_shipping:
    pattern:  /cart/checkout/set-shipping
    defaults: { _controller: MaciOrderBundle:Default:cartSetShipping }

maci_order_paypal_complete:
    pattern:  /order/paypal/complete
    defaults: { _controller: MaciOrderBundle:Default:paypalComplete }

maci_order_checkout_complete:
    pattern:  /cart/checkout/complete
    defaults: { _controller: MaciOrderBundle:Default:cartComplete }

maci_order_checkout_confirm:
    pattern:  /cart/checkout/confirm
    defaults: { _controller: MaciOrderBundle:Default:cartConfirm }

maci_order_checkout:
    pattern:  /cart/checkout
    defaults: { _controller: MaciOrderBundle:Default:cartCheckout }

maci_order_cart_form:
    pattern:  /cart/form
    defaults: { _controller: MaciOrderBundle:Default:cartForm }

maci_order_notfound:
    pattern:  /order/notfound
    defaults: { _controller: MaciOrderBundle:Default:notfound }

maci_order:
    pattern:  /user/orders
    defaults: { _controller: MaciOrderBundle:Default:index }

maci_order_cart:
    pattern:  /cart
    defaults: { _controller: MaciOrderBundle:Default:cart }

