

maci_order_checkout:
    pattern:  /order/checkout/{id}
    defaults: { _controller: MaciOrderBundle:Default:checkout }

maci_order_invoice:
    pattern:  /order/invoice/{id}
    defaults: { _controller: MaciOrderBundle:Default:invoice }

maci_order_cart_form:
    pattern:  /order/cart/form
    defaults: { _controller: MaciOrderBundle:Default:cartForm }

# PayPal Ipn Order Notification
maci_order_paypal_notification:
    pattern:  /order/paypal/ipn
    defaults: { _controller: MaciOrderBundle:Notification:ipn }

maci_order_cart_add:
    pattern:  /order/cart/add
    defaults: { _controller: MaciOrderBundle:Default:addToCart }

maci_order_cart:
    pattern:  /order/cart
    defaults: { _controller: MaciOrderBundle:Default:cart }

maci_order_notfound:
    pattern:  /order/notfound
    defaults: { _controller: MaciOrderBundle:Default:notfound }

maci_order_homepage:
    pattern:  /order
    defaults: { _controller: MaciOrderBundle:Default:index }

