
# maci_paypal_ipn:
#     path:  /ipn/ipn-twig-email-notification
#     defaults: { _controller: MaciOrderBundle:TwigNotificationEmail:index }



maci_order_cart_add:
    path:  /cart/item/add
    defaults: { _controller: MaciOrderBundle:Default:addToCart }
    methods:  [POST]

maci_order_edit_cart_item:
    path:  /cart/item/edit/{id}
    defaults: { _controller: MaciOrderBundle:Default:editCartItem }

maci_order_remove_cart_item:
    path:  /cart/item/remove/{id}
    defaults: { _controller: MaciOrderBundle:Default:removeCartItem }

maci_order_gocheckout:
    path:  /cart/gocheckout/{option}
    defaults: { _controller: MaciOrderBundle:Default:cartGoCheckout, option: checkout }

maci_order_checkout_set_checkout:
    path:  /cart/checkout/set-checkout/{checkout}
    defaults: { _controller: MaciOrderBundle:Default:cartSetCheckout, checkout: checkout }

maci_order_checkout_set_mail:
    path:  /cart/checkout/set-mail
    defaults: { _controller: MaciOrderBundle:Default:cartSetMail }

maci_order_checkout_set_billing_address:
    path:  /cart/checkout/set-billing-address
    defaults: { _controller: MaciOrderBundle:Default:cartSetBillingAddress }

maci_order_checkout_set_shipping_address:
    path:  /cart/checkout/set-shipping-address
    defaults: { _controller: MaciOrderBundle:Default:cartSetShippingAddress }

maci_order_checkout_set_payment:
    path:  /cart/checkout/set-payment
    defaults: { _controller: MaciOrderBundle:Default:cartSetPayment }

maci_order_checkout_set_shipping:
    path:  /cart/checkout/set-shipping
    defaults: { _controller: MaciOrderBundle:Default:cartSetShipping }

maci_order_paypal_complete:
    path:  /cart/checkout/complete/paypal
    defaults: { _controller: MaciOrderBundle:Default:paypalComplete }

maci_order_checkout_complete:
    path:  /cart/checkout/complete/{token}
    defaults: { _controller: MaciOrderBundle:Default:checkoutComplete }

maci_order_checkout_confirm:
    path:  /cart/checkout/confirm
    defaults: { _controller: MaciOrderBundle:Default:checkoutConfirm }

maci_order_checkout:
    path:  /cart/checkout
    defaults: { _controller: MaciOrderBundle:Default:cartCheckout }

maci_order_payments_after_capture:
    path:  /payements/after_capture
    defaults: { _controller: MaciOrderBundle:Default:afterCapture }

maci_order_cart_form:
    path:  /cart/form
    defaults: { _controller: MaciOrderBundle:Default:cartForm }

maci_order_cart:
    path:  /cart
    defaults: { _controller: MaciOrderBundle:Default:cart }



maci_order_admin_confirmed:
    path:  /admin/orders/confirmed
    defaults: { _controller: MaciOrderBundle:Default:confirmed }

maci_order_admin_show_order:
    path:  /admin/order/show/{id}
    defaults: { _controller: MaciOrderBundle:Default:adminShow }



maci_order_show:
    path:  /orders/show/{id}
    defaults: { _controller: MaciOrderBundle:Default:userShow }

maci_order_invoice:
    path:  /orders/invoice/{id}
    defaults: { _controller: MaciOrderBundle:Default:invoice }

maci_order_notfound:
    path:  /orders/notfound
    defaults: { _controller: MaciOrderBundle:Default:notfound }

maci_order:
    path:  /orders/
    defaults: { _controller: MaciOrderBundle:Default:index }
