parameters:
#    maci_order.example.class: Maci\OrderBundle\Example

services:

services:

    maci.orders:
        class: Maci\OrderBundle\Controller\OrderController
        arguments: ["@doctrine.orm.entity_manager","@security.context","@session","%maci.order.configs%","@maci.addresses"]

    maci.order.form.type.cart_add_product_item:
        class: Maci\OrderBundle\Form\Type\CartAddProductItemType
        tags:
            - { name: form.type, alias: cart_add_product_item }

    maci.order.form.type.cart_edit_item:
        class: Maci\OrderBundle\Form\Type\CartEditItemType
        tags:
            - { name: form.type, alias: cart_edit_item }

    maci.order.form.type.cart_remove_item:
        class: Maci\OrderBundle\Form\Type\CartRemoveItemType
        tags:
            - { name: form.type, alias: cart_remove_item }

    maci.order.form.type.booking:
        class: Maci\OrderBundle\Form\Type\CartBookingType
        tags:
            - { name: form.type, alias: cart_booking }

    maci.order.form.type.pickup:
        class: Maci\OrderBundle\Form\Type\CartPickupType
        tags:
            - { name: form.type, alias: cart_pickup }

    maci.order.form.type.checkout:
        class: Maci\OrderBundle\Form\Type\CartCheckoutType
        arguments: ["@maci.orders"]
        tags:
            - { name: form.type, alias: cart_checkout }

    maci.order.form.type.mail:
        class: Maci\OrderBundle\Form\Type\MailType
        tags:
            - { name: form.type, alias: order_mail }

    maci.order.form.type.payment:
        class: Maci\OrderBundle\Form\Type\PaymentType
        arguments: ["@maci.orders"]
        tags:
            - { name: form.type, alias: order_payment }

    maci.order.form.type.shipping:
        class: Maci\OrderBundle\Form\Type\ShippingType
        arguments: ["@maci.orders"]
        tags:
            - { name: form.type, alias: order_shipping }

    maci.order.paypal_im_received:
        class: Maci\OrderBundle\Event\OrderPayPalListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: paypal.ipn.receive, method: onIPNReceive }

