
services:

    # Ipn Action

    Http\Message\MessageFactory\GuzzleMessageFactory:
        arguments: []

    httplug.message_factory.guzzle:
        alias: Http\Message\MessageFactory\GuzzleMessageFactory
        public: true

    Maci\OrderBundle\Action\StoreNotificationAction:
        arguments: ["@doctrine.orm.entity_manager"]

    maci.payment.payum.action.store_notification:
        alias: Maci\OrderBundle\Action\StoreNotificationAction
        public: true

    Maci\OrderBundle\Action\StoreNotificationSandboxAction:
        arguments: ["@doctrine.orm.entity_manager"]

    maci.payment.payum.action.store_notification_sandbox:
        alias: Maci\OrderBundle\Action\StoreNotificationSandboxAction
        public: true

    # Controller Service

    Maci\OrderBundle\Controller\OrderController:
        arguments: ["@doctrine.orm.entity_manager","@security.authorization_checker",'@security.token_storage',"@session","@kernel","@maci.addresses","%maci.order.configs%"]

    maci.orders:
        alias: Maci\OrderBundle\Controller\OrderController
        public: true

    # Knp Menu
    
    maci.order.menu_builder:
        class: Maci\OrderBundle\Menu\OrderMenuBuilder
        arguments: ["@knp_menu.factory","@maci.translator"]
        tags:
            - { name: knp_menu.menu_builder, method: createShopAdminMenu, alias: shop_admin }

    # Form

    maci.order.form.type.cart_add_product_item:
        class: Maci\OrderBundle\Form\Type\CartAddProductItemType
        arguments: ["@maci.translator"]
        tags:
            - { name: form.type, alias: cart_add_product_item }

    maci.order.form.type.cart_edit_item:
        class: Maci\OrderBundle\Form\Type\CartEditItemType
        tags:
            - { name: form.type, alias: cart_edit_item }

    maci.order.form.type.cart_remove_item:
        class: Maci\OrderBundle\Form\Type\CartRemoveItemType
        tags:
            - { name: form.type, alias: cart_remove_item }

    maci.order.form.type.booking:
        class: Maci\OrderBundle\Form\Type\CartBookingType
        tags:
            - { name: form.type, alias: cart_booking }

    maci.order.form.type.pickup:
        class: Maci\OrderBundle\Form\Type\CartPickupType
        tags:
            - { name: form.type, alias: cart_pickup }

    maci.order.form.type.billing_address:
        class: Maci\OrderBundle\Form\Type\CartBillingAddressType
        arguments: ["@maci.orders","@maci.addresses"]
        tags:
            - { name: form.type, alias: cart_billing_address }

    maci.order.form.type.shipping_address:
        class: Maci\OrderBundle\Form\Type\CartShippingAddressType
        arguments: ["@maci.orders","@maci.addresses"]
        tags:
            - { name: form.type, alias: cart_shipping_address }

    maci.order.form.type.checkout:
        class: Maci\OrderBundle\Form\Type\CartCheckoutType
        arguments: ["@maci.orders"]
        tags:
            - { name: form.type, alias: cart_checkout }

    maci.order.form.type.checkout_payment:
        class: Maci\OrderBundle\Form\Type\CheckoutPaymentType
        arguments: ["@maci.orders"]
        tags:
            - { name: form.type, alias: order_checkout_payment }

    maci.order.form.type.checkout_shipping:
        class: Maci\OrderBundle\Form\Type\CheckoutShippingType
        arguments: ["@maci.orders"]
        tags:
            - { name: form.type, alias: order_checkout_shipping }

    maci.order.form.type.mail:
        class: Maci\OrderBundle\Form\Type\MailType
        tags:
            - { name: form.type, alias: order_mail }

    maci.order.form.type.payment:
        class: Maci\OrderBundle\Form\Type\PaymentType
        tags:
            - { name: form.type, alias: order_payment }

    # Orderly Bundle
    # maci.order.paypal_im_received:
    #     class: Maci\OrderBundle\Event\OrderPayPalListener
    #     arguments: ["@doctrine.orm.entity_manager"]
    #     tags:
    #         - { name: kernel.event_listener, event: paypal.ipn.receive, method: onIPNReceive }

