parameters:
#    maci_order.example.class: Maci\OrderBundle\Example

services:

  maci.order.paypal_im_received:
      class: Maci\OrderBundle\Event\OrderPayPalListener
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
          - { name: kernel.event_listener, event: paypal.ipn.receive, method: onIPNReceive }

