parameters:
#    maci_order.example.class: Maci\OrderBundle\Example

services:

services:

    maci.orders:
        class: Maci\OrderBundle\Controller\OrderController
        arguments: ["@doctrine.orm.entity_manager","@security.context","@session"]

    maci.order.paypal_im_received:
        class: Maci\OrderBundle\Event\OrderPayPalListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: paypal.ipn.receive, method: onIPNReceive }

    maci.order.form.type.mail:
        class: Maci\OrderBundle\Form\Type\MailType
        tags:
            - { name: form.type, alias: order_mail }

    maci.order.form.type.payment:
        class: Maci\OrderBundle\Form\Type\PaymentType
        tags:
            - { name: form.type, alias: order_payment }

    maci.order.form.type.spedition:
        class: Maci\OrderBundle\Form\Type\SpeditionType
        tags:
            - { name: form.type, alias: order_spedition }

